baseURL = "https://zxcv9203.github.io/"
languageCode = "ko-kr"
title = "yongckim"
theme = "github-style"
googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "yongckim"
  description = "42 cadet"
  github = "zxcv9203" # github ê³„ì •ëª…
  linkedin = "yongckim" # linked in ê³„ì •ëª…
  email = "yongckim@student.42seoul.kr"
  url = "https://zxcv9203.github.io/"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  userStatusEmoji = "ğŸ˜€"
  favicon = "/images/github.png"
  location = "korea"

#  [[params.links]] ë§í¬ ì¶”ê°€
#    title = "Link"
#    href = "https://github.com/meik2333"
#  [[params.links]]
#    title = "Link2"
#    href = "https://yongckim.github.io/"
#   	icon = "https://meik2333.com/images/avatar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]