baseURL = "https://zxcv9203.github.io/"
languageCode = "ko-kr"
title = "zxcv9203's blog"
theme = "github-style"
#googleAnalytics = "UA-123456-789"
#pygmentsCodeFences = true
#pygmentsUseClasses = true

[params]
  author = "yongckim" # ì´ë¦„
  description = "42 cadet" # ìê¸° ì†Œê°œ
  github = "zxcv9203" # github ê³„ì •ëª…
  linkedin = "yongckim" # linked in ê³„ì •ëª…
  email = "yongckim@student.42seoul.kr" #ì´ë©”ì¼
  url = "https://zxcv9203.github.io/" # ì‚¬ì´íŠ¸ ì£¼ì†Œ
  keywords = "blog, google analytics" 
  rss = true
  lastmod = true
  userStatusEmoji = "ğŸ˜€"
  favicon = "/images/github.png" # íŒŒë¹„ì½˜ì„¤ì •
  avatar = "/images/avatar.png" # ì•„ë°”íƒ€ ì„¤ì •
  location = "Korea"

  [[params.links]]
    title = "algorithm"
    href = "https://www.acmicpc.net/user/zxcv9203"
		icon = "https://zxcv9203.github.io/images/boj.png"
#  [[params.links]]  í•˜ë‹¨ ì•„ì´ì½˜ ë§í¬ ì¶”ê°€
#    title = "Link2"
#    href = "https://yongckim.github.io/"
#   	icon = "https://zxcv9203.github.io/images/avatar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]